[package]
name = "ncc_by_rust"
version = "0.1.0"
authors = ["nishio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
